apiVersion: apps/v1
kind: Deployment
metadata:
  name: qa-web
  labels:
    app: nginx-qa
  namespace: qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-qa
  template:
    metadata:
      labels:
        app: nginx-qa
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 8080